/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import lightoff_garcia_version_console.GrilleDeJeu;
import javax.swing.JButton;

/**
 *
 * @author arthurgarcia
 */
public class FenetrePrincipale extends javax.swing.JFrame {
GrilleDeJeu grille;
int nbCoups; 
private int nbColonnes;
    
    /**
     * Creates new form FenetrePrincipale
     */
    public FenetrePrincipale() {
        
       PanneauGrille = new javax.swing.JPanel();
        initComponents();
        
          int nbLignes = 16;
          int nbColonnes = 16;

PanneauBoutonsHorizontaux.setLayout(new GridLayout(1, nbColonnes));
getContentPane().add(PanneauBoutonsHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, nbColonnes * 40, 1 * 40));

for (int i = 0; i < nbColonnes; i++) {
    final int j = i;
    JButton bouton_colonne = new JButton();
    ActionListener ecouteurClick = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            grille.activerColonneDeCellules(j);
            repaint();
             verifierVictoire();
        }
    };
    bouton_colonne.addActionListener(ecouteurClick);
    PanneauBoutonsHorizontaux.add(bouton_colonne);

}

           PanneauBoutonsVerticaux.setLayout(new GridLayout(nbLignes, 1));
        getContentPane().add( PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 1 * 40, nbLignes * 40));
        // création du panneau de boutons verticaux (pour les lignes)

        for (int i = 0; i < nbLignes; i++) {
    final int j = i; // déclarer j comme effectivement finale
    JButton bouton_ligne = new JButton();
    ActionListener ecouteurClick = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            grille.activerLigneDeCellules(j);
            repaint();
             verifierVictoire();
        }
    };
    bouton_ligne.addActionListener(ecouteurClick);
    PanneauBoutonsVerticaux.add(bouton_ligne);
   
}
     // création du panneau de boutons verticaux (pour les lignes)

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100,
    nbColonnes*40, nbLignes*40));
    this.pack();
    this.revalidate();
    this.grille = new GrilleDeJeu(nbLignes, nbColonnes);
grille.cellulesToutesEteintes();
 grille.melangerMatriceAleatoirement(10);
    PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));
    for (int i=0; i < nbLignes; i++) {
    for (int j=0; j < nbColonnes; j++ ) {
   CelluleGraphique bouton_cellule = new CelluleGraphique( grille.matriceCellules[i][j], 36,36); 
   PanneauGrille.add(bouton_cellule); // ajout au Jpanel PanneauGrille

 }
    }      
getContentPane().add(diagonale_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20,
    50, 40));
diagonale_D.setText("DD");
diagonale_D.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
            grille.activerDiagonaleDescendante();
            repaint();
            verifierVictoire();
        
    }
}); 
getContentPane().add(diagonale_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60
        ,
    50, 40));
diagonale_M.setText("DM");
diagonale_M.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
            grille.activerDiagonaleMontante();
            repaint();
            verifierVictoire();
        
    }
}); 
 }
  

    private void verifierVictoire() {
        if (grille.cellulesToutesEteintes()) {
            dispose();
          new FenetreVictoire().setVisible(true);



        }
    }

 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanneauGrille = new javax.swing.JPanel();
        PanneauBoutonsVerticaux = new javax.swing.JPanel();
        PanneauBoutonsHorizontaux = new javax.swing.JPanel();
        diagonale_D = new javax.swing.JButton();
        diagonale_M = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 360, 340));

        javax.swing.GroupLayout PanneauBoutonsVerticauxLayout = new javax.swing.GroupLayout(PanneauBoutonsVerticaux);
        PanneauBoutonsVerticaux.setLayout(PanneauBoutonsVerticauxLayout);
        PanneauBoutonsVerticauxLayout.setHorizontalGroup(
            PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        PanneauBoutonsVerticauxLayout.setVerticalGroup(
            PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 40, 340));

        javax.swing.GroupLayout PanneauBoutonsHorizontauxLayout = new javax.swing.GroupLayout(PanneauBoutonsHorizontaux);
        PanneauBoutonsHorizontaux.setLayout(PanneauBoutonsHorizontauxLayout);
        PanneauBoutonsHorizontauxLayout.setHorizontalGroup(
            PanneauBoutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        PanneauBoutonsHorizontauxLayout.setVerticalGroup(
            PanneauBoutonsHorizontauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonsHorizontaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 360, 40));

        diagonale_D.setText("jButton1");
        diagonale_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagonale_DActionPerformed(evt);
            }
        });
        getContentPane().add(diagonale_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 60, -1));

        diagonale_M.setText("jButton2");
        getContentPane().add(diagonale_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 50, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diagonale_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagonale_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diagonale_DActionPerformed
  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FenetreBienvenue().setVisible(true);
            }
  

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauBoutonsHorizontaux;
    private javax.swing.JPanel PanneauBoutonsVerticaux;
    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JButton diagonale_D;
    private javax.swing.JButton diagonale_M;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables



}